landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
slug: lf-ai-foundation
landscapeMemberCategory: LF AI & Data Member Company
