landscapeMemberClasses:
   - name: Premier Membership
     category: Premier
   - name: General Membership
     category: General
   - name: Associate Membership
     category: Associate
slug: lf-ai-foundation
landscapeProjectsCategory: LF AI & Data Projects
landscapeProjectsSubcategories:
  - name: Graduated
    category: Graduated
  - name: Incubating
    category: Incubating
  - name: Sandbox
    category: Sandbox
  - name: Archived
    category: Archived
landscapeProjectsLevels:
  - level: graduated
    name: Graduated
  - level: incubating
    name: Incubating
  - level: sandbox
    name: Sandbox
  - level: archived
    name: Archived
projectsDefaultCrunchbase: https://www.crunchbase.com/organization/lf-artificial-intelligence-foundation
landscapeMemberCategory: LF AI & Data Member Company
