blank_issues_enabled: false
contact_links:
  - name: Update project or member organization information
    url: https://members.aousd.org
    about: Make a request to have project or member organization information updated directly with the LF staff
