name: Update members

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 4 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Landscape
        uses: actions/checkout@v2
        with:
          path: landscape
      - name: Checkout landscape-tools
        uses: actions/checkout@v2
        with:
          repository: jmertic/landscape-tools
          path: landscape-tools
      - name: Set up Python 3.x
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r landscape-tools/requirements.txt
      - name: Run build
        working-directory: ./landscape
        run: |
          ../landscape-tools/landscapemembers.py
      - name: Save missing.csv file
        uses: actions/upload-artifact@v2
        with:
          name: missing-members 
          path: ./landscape/missing.csv
      - name: Checkout landscapeapp
        uses: actions/checkout@v3
        with:
          repository: cncf/landscapeapp
          path: landscapeapp
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Cleanup YAML files
        working-directory: ./landscapeapp
        run: |
          node tools/removePuppeteer
          npm install
          PROJECT_PATH=../landscape node tools/removeQuotes
          PROJECT_PATH=../landscape node tools/pruneExtraEntries
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          token: ${{ secrets.PAT }}
          branch-suffix: timestamp
          path: ./landscape
          title: Update members
          labels: automated-build
          commit-message: Update members
